Fix/cambios_para_front
JulianSima/wordle-helper pull request #30
Opened 2022-05-08 20:18 UTC by matiasanz

2022-05-10 19:44 UTC, AgustinCragno requested changes

2022-05-10 19:44 UTC, AgustinCragno commented on src/main/java/com/tacs2022/wordlehelper/controller/TournamentController.java
> +		User participant = userService.findByUsername(body.getParticipantName());
@matiasanz cual era la idea de este cambio? me suena raro buscar al user por el nombre y no por el id, que pasa si dos usuarios tienen mismo nombre? deberiamos cambiar a que esa sea la pk si queremos hacer algo asi.

2022-05-10 19:44 UTC, AgustinCragno commented on src/main/java/com/tacs2022/wordlehelper/service/TournamentService.java
> +
@matiasanz antes de mergear fijate que yo hace poco estuve haciendo muchos cambios en esta clase, cuando puedas miralo creo que ya esta mergeado, y cualquier cosa hablamos que es lo que queda

2022-05-12 22:15 UTC, matiasanz commented on src/main/java/com/tacs2022/wordlehelper/controller/TournamentController.java
> +		User participant = userService.findByUsername(body.getParticipantName());
@AgusCragno Julián me habia pedido que cambie ese metodo, porque desde el front no tenia forma de saber el id del usuario. De la forma que esta, se lo damos unicamente cuando se registra, y despues se lo devolvemos en el token hasheado.

Por otra parte, en el userService estamos validando que los nombres de usuarios no se repitan.

Perdon que contesto ahora, no lo habia visto.

2022-05-12 23:23 UTC, AgustinCragno approved these changes

2022-05-12 23:24 UTC, merged